Repository wildxmxtt/spotbot2, pull requests merged in 2024-08, with the labels that each got.

#8 Merge documentation to main
  README.md
Labels: documentation

#6 Merge wavecodes into main
  spotbot.py
Labels: enhancement

#7 SpotBot Leaderboard and Achievements
  achievements.py
  app.py
  database.py
  playlist_update.py
  spotbot.db
  spotbot.py
Labels: enhancement

#9 Database initialization
  spotbot.py
Labels: bug
